[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doryen-rs = "1.3.0"
rand = "0.8.5"
specs = { version = "0.19.0", features = ["specs-derive"] }
